name: Analyze, Build and Deploy

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build-singularity-container:
    name: Build Singularity container
    runs-on: ubuntu-latest # quay.io/singularity/singularity
    steps:
    - name: Install
      run: |
        sudo apt-get update
